name: roman-data-workshop-env

dependencies:
  - jupyter
  - notebook >= 6.0
  - matplotlib >= 3.2
  - ipympl
  - numpy >= 1.20
  - packaging
  - pip
  - python >= 3.9
  - pyyaml
  - pip:
      - asdf_standard
      - asdf
      - asdf-astropy
      - astropy >= 5.3
      - gwcs >= 0.20
      - stpipe
      - romancal >= 0.13
